name: Move assigned issues into In progress

on:
  issues:
    types: [assigned]

jobs:
  automate-project-columns:
    runs-on: ubuntu-latest
    steps:
      - uses: alex-page/github-project-automation-plus@v0.3.0
        with:
          project: Phase 1
          column: In progress
          repo-token: ${{ secrets.GITHUB_TOKEN }}